### PR TITLE
7.10 compatibility

### PR DESCRIPTION
**Pull request by thumphries**
See ambiata/yak#63

Rename cabal file, loosen `time` constraint.

Builds in 7.10 once the `p` submodule is bumped, i.e. blocked by ambiata/p#55

### CODE REVIEW

**Comment by jystic** [comment]
I think this should be good to go now - might be good to get the build going for 7.10.2 though.

**Comment by jystic** [comment]
Actually this probably needs https://github.com/ambiata/disorder.hs/pull/54 to get finished off

**Comment by jystic** [comment]
ok, now this should be all set! /cc @thumphries

**Comment by thumphries** [comment]
:shaved_ice:

**Pull request merged**
