### PR TITLE
Support GHC 8.0.1

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Also adds boris configuration.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@jystic @nhibberd

**Comment by jystic** [comment]
@nhibberd what's the plan with boris 7.10 / 8.0 builds? are they production ready yet, or still some kinks to work out?

**Comment by markhibberd** [comment]
The image is now baked, so they "should" be all ok with new master runner. "should" being the description for some random strings that have never actually run but look like they might do the job. I will test it end to end this morning.

**Comment by jystic** [comment]
👍 for the 8.0.1 stuff

maybe for the boris file it should look more like [this](https://github.com/ambiata/p/blob/master/boris.toml#L4)

**Comment by tmcgilchrist** [comment]
Updated to include all the boris builds.

**Comment by nhibberd** [comment]
@tmcgilchrist @jystic need to take our time with these, the Boris configuration is not correct. Your boris-git needs to line up with your boris.toml

**Comment by nhibberd** [comment]
And also your master file

**Pull request merged**
